# Generated by Django 3.2.13 on 2022-05-20 09:18

from django.db import migrations, models
import django_resized.forms
import radio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('artwork', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, size=[500, 500], upload_to='audios/cover/%Y/%m/%d/', validators=[radio.models.validate_file_extension], verbose_name='کاور')),
                ('url', models.FileField(upload_to='audios/', verbose_name='انتخاب فایل صوتی')),
                ('sort', models.IntegerField(verbose_name='موقعیت')),
                ('date', models.DateTimeField(verbose_name='تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به روز رسانی')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'لیست پخش',
            },
        ),
    ]
